---
route:
  group_by: ['alertname', 'cluster', 'service']
  receiver: default-telegram
  routes:
    - match:
        severity: critical
      receiver: critical-telegram
receivers:
  - name: critical-telegram
    telegram_configs:
      - bot_token: 6671343843:AAFVgofqkTCfgFO7kfaJ_9edOe2Zs-f6CfE
        api_url: https://api.telegram.org
        chat_id: -1001749694053
        parse_mode: ""
  - name: default-telegram
    telegram_configs:
      - bot_token: 6671343843:AAFVgofqkTCfgFO7kfaJ_9edOe2Zs-f6CfE
        api_url: https://api.telegram.org
        chat_id: -1001749694053
        parse_mode: ""