---
version: '3.8'

networks:
  front-tier:
  back-tier:


services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - back-tier

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox_exporter
    volumes:
      - ./blackbox/:/etc/blackbox/

    command:
      - '--config.file=/etc/blackbox/blackbox.yml'
    restart: unless-stopped
    networks:
      - back-tier

  mysqld_exporter:
    image: quay.io/prometheus/mysqld-exporter:latest
    container_name: mysqld_exporter
    volumes:
      - ./mysqld/:/etc/mysqld/
    command:
      - '--config.my-cnf=/etc/mysqld/mysqld.conf'
    restart: unless-stopped
    ports:
      - "9104:9104"
    networks:
      - back-tier
  php-fpm-exporter:
#    image: drud/php-fpm-exporter:v0.25.5
    image: hipages/php-fpm_exporter:latest
    container_name: php-fpm-exporter
    hostname: php-fpm-exporter
    ports:
      - 9253:9253
    volumes:
      - '/run/php/php8.2-fpm.sock:/tmp/php.sock'
    command:
      - '--log.level=info'
#      - '--phpfpm.scrape-uri=tcp://192.168.56.104/status'
      - '--phpfpm.scrape-uri=unix:///tmp/php.sock;/status'
    networks:
      - back-tier
